# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 410)
        self.username_label = QtWidgets.QLabel(parent=Dialog)
        self.username_label.setGeometry(QtCore.QRect(60, 10, 101, 31))
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(parent=Dialog)
        self.password_label.setGeometry(QtCore.QRect(60, 86, 91, 31))
        self.password_label.setObjectName("password_label")
        self.username_input = QtWidgets.QLineEdit(parent=Dialog)
        self.username_input.setGeometry(QtCore.QRect(60, 50, 113, 31))
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(parent=Dialog)
        self.password_input.setGeometry(QtCore.QRect(60, 130, 113, 31))
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.login_Btn = QtWidgets.QPushButton(parent=Dialog)
        self.login_Btn.setGeometry(QtCore.QRect(80, 170, 101, 41))
        self.login_Btn.setObjectName("login_Btn")
        self.cancel_Btn = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_Btn.setGeometry(QtCore.QRect(210, 170, 121, 41))
        self.cancel_Btn.setObjectName("cancel_Btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.username_label.setText(_translate("Dialog", "Username:"))
        self.password_label.setText(_translate("Dialog", "Password:"))
        self.login_Btn.setText(_translate("Dialog", "Login"))
        self.cancel_Btn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
